# Generated by Django 4.0 on 2021-12-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notogri',
            old_name='togrisi',
            new_name='t_soz',
        ),
        migrations.RenameField(
            model_name='togri',
            old_name='t_soz',
            new_name='soz',
        ),
    ]
